name: "draft-release"

on:
  workflow_dispatch:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do Something
        id: do-something-id
        shell: bash
        run: |
          content=$(cat details-summary-example.md)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "some_output=content" >> $GITHUB_OUTPUT 
      - name: Create draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.do-something-id.outputs.some_output}}
          draft: true
          generate_release_notes: true


