name: "draft-release"

on:
  workflow_dispatch:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do Something
        id: do-something-id
        shell: bash
        run: |
          content=`cat details-summary-example.md | tee gen-details-summary-example.md`

      - name: get latest release tag
        id: latest-release-tag
        shell: bash
        run: |
          gh auth status
          latest_tag=$(gh release list --exclude-drafts --exclude-pre-releases --limit 1 | awk '{print $1}')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create draft release
        shell: bash
        run: |
          gh auth status
          cat gen-details-summary-example.md | gh release create ${{ github.ref_name }} --verify-tag --draft --generate-notes --notes-start-tag ${{ steps.latest-release-tag.outputs.LATEST_TAG }} --notes-file -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
