name: "draft-release"

on:
  workflow_dispatch:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do Something
        id: do-something-id
        shell: bash
        run: |
          content=`cat details-summary-example.md | tee gen-details-summary-example.md`
      - name: get release tag
        id: latest-release-tag
        shell: bash
        run: |
          gh auth status
          latest_tag=$(gh release list --exclude-drafts --exclude-pre-releases --limit 1 | awk '{print $1}')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT
          echo $LATEST_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: generate change log
        id: change_log
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: ${{ steps.latest-release-tag.outputs.LATEST_TAG}}
      - name: Create draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.change_log.outputs.changelog}}
          # body_path: gen-details-summary-example.md
          draft: true
          # generate_release_notes: true


