name: "draft-release"

on:
  workflow_dispatch:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do Something
        id: do-something-id
        shell: bash
        run: |
          {
            echo 'some_output<<EOF'
            cat details-summary-example.md
            echo EOF
          } >> $GITHUB_OUTPUT 
      - name: Create draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.do-something-id.outputs.some_output}}
          draft: true
          generate_release_notes: true


